// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Repositories.Models;

public partial class Account
{
    public long Id { get; set; }

    public string AccountName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public bool? IsActive { get; set; }

    public string Role { get; set; }

    public int? PointBalance { get; set; }

    public virtual ICollection<Consignment> Consignments { get; set; } = new List<Consignment>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}