// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Repositories.Models;

public partial class Consignment
{
    public long Id { get; set; }

    public long? KoiId { get; set; }

    public long? AccountId { get; set; }

    public long? ConsignmentType { get; set; }

    public long? ConsignmentDuration { get; set; }

    public DateTime? ConsignmentStartDate { get; set; }

    public string ConsignmentStatus { get; set; }

    public string ConsignPaymentStatus { get; set; }

    public string ConsignPaymentMethod { get; set; }

    public double? ConsignOverdueFee { get; set; }

    public long? ConsignOverdueDuration { get; set; }

    public virtual Account Account { get; set; }

    public virtual Koi Koi { get; set; }
}