// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Repositories.Models;

public partial class KoiFarm
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public string PhoneNumber { get; set; }

    public string Description { get; set; }

    public long? OwnerId { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public string Image { get; set; }

    public string AwardImage { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Koi> Kois { get; set; } = new List<Koi>();
}