// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Repositories.Models;

public partial class KoiQualification
{
    public int Id { get; set; }

    public int? KoiId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string Image { get; set; }

    public string IssueBy { get; set; }

    public DateTime? IssueDate { get; set; }

    public DateTime? ExpiredDate { get; set; }

    public string ValidationStatus { get; set; }

    public string Description { get; set; }

    public DateTime? CreateAt { get; set; }

    public virtual Koi Koi { get; set; }
}