// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Repositories.Models;

public partial class Order
{
    public long Id { get; set; }

    public long? AccountId { get; set; }

    public string CustomerName { get; set; }

    public string OrderPhoneNumber { get; set; }

    public string OrderAdress { get; set; }

    public string Notes { get; set; }

    public int? TotalAmount { get; set; }

    public string OrderStatus { get; set; }

    public int? TotalQuantity { get; set; }

    public double? TotalWeight { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}