// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Repositories.Models;

public partial class OrderDetail
{
    public long Id { get; set; }

    public long? OrderId { get; set; }

    public long? KoiId { get; set; }

    public virtual Koi Koi { get; set; }

    public virtual Order Order { get; set; }
}