// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Repositories.Models;

public partial class Promotion
{
    public long Id { get; set; }

    public string PromotionName { get; set; }

    public string Description { get; set; }

    public double? DiscountPercentage { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool? IsActive { get; set; }

    public long? MinimumOrderValue { get; set; }

    public double? MaximumDiscountAmount { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<Koi> Kois { get; set; } = new List<Koi>();
}